#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 153
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_SEMI = 2,
  aux_sym_exp_token1 = 3,
  anon_sym_PLUS = 4,
  anon_sym_STAR = 5,
  anon_sym_DASH = 6,
  anon_sym_COMMA = 7,
  anon_sym_GT = 8,
  anon_sym_LT = 9,
  anon_sym_EQ = 10,
  sym_true = 11,
  sym_false = 12,
  sym_not = 13,
  anon_sym_and = 14,
  anon_sym_or = 15,
  sym_skip = 16,
  sym_begin = 17,
  sym_end = 18,
  sym_while = 19,
  sym_do = 20,
  sym_if = 21,
  sym_then = 22,
  sym_else = 23,
  anon_sym_COLON_EQ = 24,
  anon_sym_LPAREN = 25,
  anon_sym_RPAREN = 26,
  sym_procedure = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_array = 30,
  sym_class = 31,
  sym_method = 32,
  sym_new = 33,
  anon_sym_DASH_GT = 34,
  anon_sym_DOT = 35,
  sym_print = 36,
  aux_sym_comment_token1 = 37,
  sym_prog = 38,
  sym_statement_list = 39,
  sym_statement = 40,
  sym_exp = 41,
  sym_exp_list = 42,
  sym_boolexp = 43,
  sym_logic_bin = 44,
  sym_block = 45,
  sym_while_loop = 46,
  sym_if_stmt = 47,
  sym_var = 48,
  sym_lval = 49,
  sym_var_assgt = 50,
  sym_rval = 51,
  sym_var_list = 52,
  sym_var_decllist = 53,
  sym_proc_decl = 54,
  sym_fun = 55,
  sym_proc_call = 56,
  sym_new_arr = 57,
  sym_arr_idx = 58,
  sym_class_decl = 59,
  sym_classname = 60,
  sym_method_decl = 61,
  sym_new_obj = 62,
  sym_field = 63,
  sym_fieldlab = 64,
  sym_method_call = 65,
  sym_print_stmt = 66,
  sym_comment = 67,
  aux_sym_statement_list_repeat1 = 68,
  aux_sym_statement_list_repeat2 = 69,
  aux_sym_exp_list_repeat1 = 70,
  aux_sym_var_list_repeat1 = 71,
  aux_sym_var_decllist_repeat1 = 72,
  aux_sym_class_decl_repeat1 = 73,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_SEMI] = ";",
  [aux_sym_exp_token1] = "exp_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_skip] = "skip",
  [sym_begin] = "begin",
  [sym_end] = "end",
  [sym_while] = "while",
  [sym_do] = "do",
  [sym_if] = "if",
  [sym_then] = "then",
  [sym_else] = "else",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_procedure] = "procedure",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_array] = "array",
  [sym_class] = "class",
  [sym_method] = "method",
  [sym_new] = "new",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DOT] = ".",
  [sym_print] = "print",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_prog] = "prog",
  [sym_statement_list] = "statement_list",
  [sym_statement] = "statement",
  [sym_exp] = "exp",
  [sym_exp_list] = "exp_list",
  [sym_boolexp] = "boolexp",
  [sym_logic_bin] = "logic_bin",
  [sym_block] = "block",
  [sym_while_loop] = "while_loop",
  [sym_if_stmt] = "if_stmt",
  [sym_var] = "var",
  [sym_lval] = "lval",
  [sym_var_assgt] = "var_assgt",
  [sym_rval] = "rval",
  [sym_var_list] = "var_list",
  [sym_var_decllist] = "var_decllist",
  [sym_proc_decl] = "proc_decl",
  [sym_fun] = "fun",
  [sym_proc_call] = "proc_call",
  [sym_new_arr] = "new_arr",
  [sym_arr_idx] = "arr_idx",
  [sym_class_decl] = "class_decl",
  [sym_classname] = "classname",
  [sym_method_decl] = "method_decl",
  [sym_new_obj] = "new_obj",
  [sym_field] = "field",
  [sym_fieldlab] = "fieldlab",
  [sym_method_call] = "method_call",
  [sym_print_stmt] = "print_stmt",
  [sym_comment] = "comment",
  [aux_sym_statement_list_repeat1] = "statement_list_repeat1",
  [aux_sym_statement_list_repeat2] = "statement_list_repeat2",
  [aux_sym_exp_list_repeat1] = "exp_list_repeat1",
  [aux_sym_var_list_repeat1] = "var_list_repeat1",
  [aux_sym_var_decllist_repeat1] = "var_decllist_repeat1",
  [aux_sym_class_decl_repeat1] = "class_decl_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_exp_token1] = aux_sym_exp_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_not] = sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_skip] = sym_skip,
  [sym_begin] = sym_begin,
  [sym_end] = sym_end,
  [sym_while] = sym_while,
  [sym_do] = sym_do,
  [sym_if] = sym_if,
  [sym_then] = sym_then,
  [sym_else] = sym_else,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_procedure] = sym_procedure,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_array] = sym_array,
  [sym_class] = sym_class,
  [sym_method] = sym_method,
  [sym_new] = sym_new,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_print] = sym_print,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_prog] = sym_prog,
  [sym_statement_list] = sym_statement_list,
  [sym_statement] = sym_statement,
  [sym_exp] = sym_exp,
  [sym_exp_list] = sym_exp_list,
  [sym_boolexp] = sym_boolexp,
  [sym_logic_bin] = sym_logic_bin,
  [sym_block] = sym_block,
  [sym_while_loop] = sym_while_loop,
  [sym_if_stmt] = sym_if_stmt,
  [sym_var] = sym_var,
  [sym_lval] = sym_lval,
  [sym_var_assgt] = sym_var_assgt,
  [sym_rval] = sym_rval,
  [sym_var_list] = sym_var_list,
  [sym_var_decllist] = sym_var_decllist,
  [sym_proc_decl] = sym_proc_decl,
  [sym_fun] = sym_fun,
  [sym_proc_call] = sym_proc_call,
  [sym_new_arr] = sym_new_arr,
  [sym_arr_idx] = sym_arr_idx,
  [sym_class_decl] = sym_class_decl,
  [sym_classname] = sym_classname,
  [sym_method_decl] = sym_method_decl,
  [sym_new_obj] = sym_new_obj,
  [sym_field] = sym_field,
  [sym_fieldlab] = sym_fieldlab,
  [sym_method_call] = sym_method_call,
  [sym_print_stmt] = sym_print_stmt,
  [sym_comment] = sym_comment,
  [aux_sym_statement_list_repeat1] = aux_sym_statement_list_repeat1,
  [aux_sym_statement_list_repeat2] = aux_sym_statement_list_repeat2,
  [aux_sym_exp_list_repeat1] = aux_sym_exp_list_repeat1,
  [aux_sym_var_list_repeat1] = aux_sym_var_list_repeat1,
  [aux_sym_var_decllist_repeat1] = aux_sym_var_decllist_repeat1,
  [aux_sym_class_decl_repeat1] = aux_sym_class_decl_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_exp_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_skip] = {
    .visible = true,
    .named = true,
  },
  [sym_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_do] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_then] = {
    .visible = true,
    .named = true,
  },
  [sym_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_new] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_print] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_prog] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_list] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym_exp_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolexp] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_bin] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_while_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_if_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_lval] = {
    .visible = true,
    .named = true,
  },
  [sym_var_assgt] = {
    .visible = true,
    .named = true,
  },
  [sym_rval] = {
    .visible = true,
    .named = true,
  },
  [sym_var_list] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decllist] = {
    .visible = true,
    .named = true,
  },
  [sym_proc_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_proc_call] = {
    .visible = true,
    .named = true,
  },
  [sym_new_arr] = {
    .visible = true,
    .named = true,
  },
  [sym_arr_idx] = {
    .visible = true,
    .named = true,
  },
  [sym_class_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_classname] = {
    .visible = true,
    .named = true,
  },
  [sym_method_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_new_obj] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fieldlab] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_print_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_list_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exp_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_decllist_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_branchOn = 3,
  field_declarations = 4,
  field_doBlock = 5,
  field_elseBlock = 6,
  field_methodName = 7,
  field_name = 8,
  field_object = 9,
  field_params = 10,
  field_thenBlock = 11,
  field_whileCond = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_branchOn] = "branchOn",
  [field_declarations] = "declarations",
  [field_doBlock] = "doBlock",
  [field_elseBlock] = "elseBlock",
  [field_methodName] = "methodName",
  [field_name] = "name",
  [field_object] = "object",
  [field_params] = "params",
  [field_thenBlock] = "thenBlock",
  [field_whileCond] = "whileCond",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 1},
  [10] = {.index = 18, .length = 4},
  [11] = {.index = 22, .length = 2},
  [12] = {.index = 24, .length = 2},
  [13] = {.index = 26, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_doBlock, 3},
    {field_whileCond, 1},
  [4] =
    {field_args, 2},
    {field_name, 0},
  [6] =
    {field_methodName, 2},
    {field_object, 0},
  [8] =
    {field_branchOn, 1},
    {field_elseBlock, 5},
    {field_thenBlock, 3},
  [11] =
    {field_args, 4},
    {field_methodName, 2},
    {field_object, 0},
  [14] =
    {field_body, 6},
    {field_name, 1},
    {field_params, 3},
  [17] =
    {field_name, 1},
  [18] =
    {field_body, 7},
    {field_declarations, 6},
    {field_name, 1},
    {field_params, 3},
  [22] =
    {field_name, 1},
    {field_params, 3},
  [24] =
    {field_body, 5},
    {field_name, 1},
  [26] =
    {field_body, 6},
    {field_declarations, 5},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '%', 24,
        '(', 18,
        ')', 19,
        '*', 9,
        '+', 8,
        ',', 12,
        '-', 11,
        '.', 23,
        ':', 2,
        ';', 6,
        '<', 14,
        '=', 15,
        '>', 13,
        '[', 20,
        ']', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '-') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '%', 24,
        '(', 18,
        ')', 19,
        '*', 9,
        '+', 8,
        ',', 12,
        '-', 3,
        '.', 23,
        ':', 2,
        ';', 6,
        '<', 14,
        '=', 15,
        '>', 13,
        '[', 20,
        ']', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'm', 8,
        'n', 9,
        'o', 10,
        'p', 11,
        's', 12,
        't', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'k') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(30);
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_do);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_if);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'w') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_end);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'h') ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_new);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_not);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'y') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_else);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_skip);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_then);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_array);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_begin);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_class);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_print);
      END_STATE();
    case 67:
      if (lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_while);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_method);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_procedure);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym_exp_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_skip] = ACTIONS(1),
    [sym_begin] = ACTIONS(1),
    [sym_end] = ACTIONS(1),
    [sym_while] = ACTIONS(1),
    [sym_do] = ACTIONS(1),
    [sym_if] = ACTIONS(1),
    [sym_then] = ACTIONS(1),
    [sym_else] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_procedure] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_array] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [sym_method] = ACTIONS(1),
    [sym_new] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_print] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_prog] = STATE(132),
    [sym_statement_list] = STATE(149),
    [sym_statement] = STATE(48),
    [sym_block] = STATE(69),
    [sym_while_loop] = STATE(69),
    [sym_if_stmt] = STATE(69),
    [sym_var] = STATE(9),
    [sym_lval] = STATE(96),
    [sym_var_assgt] = STATE(69),
    [sym_proc_decl] = STATE(69),
    [sym_fun] = STATE(148),
    [sym_proc_call] = STATE(69),
    [sym_new_arr] = STATE(69),
    [sym_arr_idx] = STATE(11),
    [sym_class_decl] = STATE(69),
    [sym_new_obj] = STATE(69),
    [sym_field] = STATE(45),
    [sym_method_call] = STATE(69),
    [sym_print_stmt] = STATE(69),
    [sym_comment] = STATE(35),
    [aux_sym_statement_list_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ident] = ACTIONS(5),
    [sym_skip] = ACTIONS(7),
    [sym_begin] = ACTIONS(9),
    [sym_while] = ACTIONS(11),
    [sym_if] = ACTIONS(13),
    [sym_procedure] = ACTIONS(15),
    [sym_array] = ACTIONS(17),
    [sym_class] = ACTIONS(19),
    [sym_print] = ACTIONS(21),
    [aux_sym_comment_token1] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(11), 1,
      sym_while,
    ACTIONS(13), 1,
      sym_if,
    ACTIONS(15), 1,
      sym_procedure,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(19), 1,
      sym_class,
    ACTIONS(21), 1,
      sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(3), 1,
      aux_sym_statement_list_repeat1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(35), 1,
      sym_comment,
    STATE(45), 1,
      sym_field,
    STATE(48), 1,
      sym_statement,
    STATE(96), 1,
      sym_lval,
    STATE(130), 1,
      sym_statement_list,
    STATE(148), 1,
      sym_fun,
    STATE(69), 11,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
  [71] = 19,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(11), 1,
      sym_while,
    ACTIONS(13), 1,
      sym_if,
    ACTIONS(15), 1,
      sym_procedure,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(19), 1,
      sym_class,
    ACTIONS(21), 1,
      sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(4), 1,
      aux_sym_statement_list_repeat1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(32), 1,
      sym_comment,
    STATE(45), 1,
      sym_field,
    STATE(54), 1,
      sym_statement,
    STATE(96), 1,
      sym_lval,
    STATE(148), 1,
      sym_fun,
    STATE(69), 11,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
  [139] = 19,
    ACTIONS(25), 1,
      sym_ident,
    ACTIONS(28), 1,
      sym_skip,
    ACTIONS(31), 1,
      sym_begin,
    ACTIONS(34), 1,
      sym_while,
    ACTIONS(37), 1,
      sym_if,
    ACTIONS(40), 1,
      sym_procedure,
    ACTIONS(43), 1,
      sym_array,
    ACTIONS(46), 1,
      sym_class,
    ACTIONS(49), 1,
      sym_print,
    ACTIONS(52), 1,
      aux_sym_comment_token1,
    STATE(4), 1,
      aux_sym_statement_list_repeat1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(39), 1,
      sym_comment,
    STATE(45), 1,
      sym_field,
    STATE(96), 1,
      sym_lval,
    STATE(127), 1,
      sym_statement,
    STATE(148), 1,
      sym_fun,
    STATE(69), 11,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
  [207] = 17,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(11), 1,
      sym_while,
    ACTIONS(13), 1,
      sym_if,
    ACTIONS(15), 1,
      sym_procedure,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(19), 1,
      sym_class,
    ACTIONS(21), 1,
      sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(45), 1,
      sym_field,
    STATE(65), 1,
      sym_statement,
    STATE(96), 1,
      sym_lval,
    STATE(148), 1,
      sym_fun,
    STATE(69), 12,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
      sym_comment,
  [270] = 17,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(11), 1,
      sym_while,
    ACTIONS(13), 1,
      sym_if,
    ACTIONS(15), 1,
      sym_procedure,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(19), 1,
      sym_class,
    ACTIONS(21), 1,
      sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(45), 1,
      sym_field,
    STATE(96), 1,
      sym_lval,
    STATE(128), 1,
      sym_statement,
    STATE(148), 1,
      sym_fun,
    STATE(69), 12,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
      sym_comment,
  [333] = 17,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(11), 1,
      sym_while,
    ACTIONS(13), 1,
      sym_if,
    ACTIONS(15), 1,
      sym_procedure,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(19), 1,
      sym_class,
    ACTIONS(21), 1,
      sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_arr_idx,
    STATE(45), 1,
      sym_field,
    STATE(71), 1,
      sym_statement,
    STATE(96), 1,
      sym_lval,
    STATE(148), 1,
      sym_fun,
    STATE(69), 12,
      sym_block,
      sym_while_loop,
      sym_if_stmt,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print_stmt,
      sym_comment,
  [396] = 2,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      aux_sym_comment_token1,
  [423] = 2,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(59), 20,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [449] = 1,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_begin,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [473] = 1,
    ACTIONS(59), 20,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [496] = 1,
    ACTIONS(63), 20,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [519] = 1,
    ACTIONS(65), 20,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [542] = 1,
    ACTIONS(67), 20,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_COLON_EQ,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      aux_sym_comment_token1,
  [565] = 2,
    ACTIONS(59), 2,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(69), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [589] = 3,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_DASH_GT,
    ACTIONS(69), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [615] = 1,
    ACTIONS(69), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [635] = 1,
    ACTIONS(75), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [655] = 1,
    ACTIONS(77), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [675] = 1,
    ACTIONS(79), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [695] = 1,
    ACTIONS(81), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [715] = 1,
    ACTIONS(83), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [735] = 1,
    ACTIONS(85), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_and,
      anon_sym_or,
      sym_end,
      sym_do,
      sym_then,
      sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [755] = 13,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      sym_not,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(57), 1,
      sym_exp,
    STATE(82), 1,
      sym_boolexp,
    STATE(148), 1,
      sym_fun,
    ACTIONS(91), 2,
      sym_true,
      sym_false,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [797] = 13,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      sym_not,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(57), 1,
      sym_exp,
    STATE(79), 1,
      sym_boolexp,
    STATE(148), 1,
      sym_fun,
    ACTIONS(91), 2,
      sym_true,
      sym_false,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [839] = 13,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      sym_not,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(57), 1,
      sym_exp,
    STATE(81), 1,
      sym_boolexp,
    STATE(148), 1,
      sym_fun,
    ACTIONS(91), 2,
      sym_true,
      sym_false,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [881] = 14,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(17), 1,
      sym_array,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(95), 1,
      sym_new,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(47), 1,
      sym_exp,
    STATE(60), 1,
      sym_rval,
    STATE(61), 1,
      sym_new_arr,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [925] = 13,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      sym_not,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(57), 1,
      sym_exp,
    STATE(64), 1,
      sym_boolexp,
    STATE(148), 1,
      sym_fun,
    ACTIONS(91), 2,
      sym_true,
      sym_false,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [967] = 2,
    ACTIONS(99), 1,
      sym_ident,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_skip,
      sym_begin,
      sym_end,
      sym_while,
      sym_if,
      sym_else,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
      aux_sym_comment_token1,
  [986] = 5,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
    ACTIONS(105), 8,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
  [1011] = 5,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(68), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
    ACTIONS(105), 8,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
  [1036] = 4,
    ACTIONS(109), 1,
      sym_ident,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_end,
    ACTIONS(111), 2,
      anon_sym_SEMI,
      aux_sym_comment_token1,
    ACTIONS(113), 8,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
  [1058] = 12,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(62), 1,
      sym_exp,
    STATE(146), 1,
      sym_exp_list,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1096] = 12,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(62), 1,
      sym_exp,
    STATE(144), 1,
      sym_exp_list,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1134] = 4,
    ACTIONS(109), 1,
      sym_ident,
    ACTIONS(111), 2,
      anon_sym_SEMI,
      aux_sym_comment_token1,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_end,
    ACTIONS(113), 8,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
  [1156] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(90), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1188] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(46), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1220] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(102), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1252] = 3,
    ACTIONS(109), 1,
      sym_ident,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(113), 9,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
      aux_sym_comment_token1,
  [1270] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(20), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1302] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(88), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1334] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(52), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1366] = 10,
    ACTIONS(87), 1,
      aux_sym_exp_token1,
    ACTIONS(89), 1,
      anon_sym_DASH,
    ACTIONS(115), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(11), 1,
      sym_field,
    STATE(15), 1,
      sym_arr_idx,
    STATE(16), 1,
      sym_lval,
    STATE(18), 1,
      sym_exp,
    STATE(148), 1,
      sym_fun,
    STATE(17), 2,
      sym_proc_call,
      sym_method_call,
  [1398] = 2,
    ACTIONS(103), 1,
      sym_ident,
    ACTIONS(105), 9,
      sym_skip,
      sym_begin,
      sym_while,
      sym_if,
      sym_procedure,
      sym_array,
      sym_class,
      sym_print,
      aux_sym_comment_token1,
  [1413] = 2,
    ACTIONS(59), 3,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1426] = 2,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1438] = 2,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1450] = 4,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(63), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1465] = 6,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(131), 1,
      sym_ident,
    STATE(97), 1,
      aux_sym_var_decllist_repeat1,
    STATE(106), 1,
      sym_var,
    STATE(122), 1,
      sym_block,
    STATE(123), 1,
      sym_var_decllist,
  [1484] = 2,
    ACTIONS(133), 1,
      sym_ident,
    ACTIONS(135), 5,
      aux_sym_exp_token1,
      anon_sym_DASH,
      sym_true,
      sym_false,
      sym_not,
  [1495] = 1,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      anon_sym_LPAREN,
      aux_sym_comment_token1,
  [1504] = 2,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(139), 4,
      anon_sym_and,
      anon_sym_or,
      sym_do,
      sym_then,
  [1515] = 4,
    ACTIONS(141), 1,
      sym_ident,
    STATE(12), 1,
      sym_fieldlab,
    STATE(13), 1,
      sym_lval,
    STATE(11), 3,
      sym_var,
      sym_arr_idx,
      sym_field,
  [1530] = 4,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1545] = 6,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(131), 1,
      sym_ident,
    STATE(74), 1,
      sym_block,
    STATE(97), 1,
      aux_sym_var_decllist_repeat1,
    STATE(106), 1,
      sym_var,
    STATE(107), 1,
      sym_var_decllist,
  [1564] = 6,
    ACTIONS(9), 1,
      sym_begin,
    ACTIONS(131), 1,
      sym_ident,
    STATE(97), 1,
      aux_sym_var_decllist_repeat1,
    STATE(106), 1,
      sym_var,
    STATE(119), 1,
      sym_block,
    STATE(120), 1,
      sym_var_decllist,
  [1583] = 2,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(145), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
  [1593] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(59), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1605] = 3,
    ACTIONS(149), 1,
      aux_sym_comment_token1,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(59), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1617] = 1,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1625] = 1,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1633] = 4,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_exp_list_repeat1,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1647] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(59), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1659] = 3,
    STATE(28), 1,
      sym_logic_bin,
    ACTIONS(139), 2,
      sym_do,
      sym_then,
    ACTIONS(158), 2,
      anon_sym_and,
      anon_sym_or,
  [1671] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1679] = 1,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1687] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1695] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      sym_end,
    STATE(59), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1707] = 1,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1715] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1723] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1731] = 1,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1739] = 1,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1747] = 1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1755] = 1,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1763] = 1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1771] = 1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1779] = 1,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1787] = 3,
    STATE(28), 1,
      sym_logic_bin,
    ACTIONS(158), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(186), 2,
      sym_do,
      sym_then,
  [1799] = 1,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_end,
      sym_else,
      aux_sym_comment_token1,
  [1807] = 3,
    ACTIONS(190), 1,
      sym_do,
    STATE(28), 1,
      sym_logic_bin,
    ACTIONS(158), 2,
      anon_sym_and,
      anon_sym_or,
  [1818] = 3,
    ACTIONS(192), 1,
      sym_then,
    STATE(28), 1,
      sym_logic_bin,
    ACTIONS(158), 2,
      anon_sym_and,
      anon_sym_or,
  [1829] = 1,
    ACTIONS(194), 4,
      anon_sym_and,
      anon_sym_or,
      sym_do,
      sym_then,
  [1836] = 4,
    ACTIONS(196), 1,
      sym_end,
    ACTIONS(198), 1,
      sym_method,
    STATE(99), 1,
      aux_sym_class_decl_repeat1,
    STATE(109), 1,
      sym_method_decl,
  [1849] = 4,
    ACTIONS(141), 1,
      sym_ident,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_var,
    STATE(150), 1,
      sym_var_list,
  [1862] = 4,
    ACTIONS(198), 1,
      sym_method,
    ACTIONS(202), 1,
      sym_end,
    STATE(95), 1,
      aux_sym_class_decl_repeat1,
    STATE(115), 1,
      sym_method_decl,
  [1875] = 4,
    ACTIONS(141), 1,
      sym_ident,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_var,
    STATE(142), 1,
      sym_var_list,
  [1888] = 2,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(206), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1897] = 3,
    ACTIONS(208), 1,
      sym_method,
    STATE(89), 1,
      aux_sym_class_decl_repeat1,
    STATE(137), 1,
      sym_method_decl,
  [1907] = 2,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1915] = 3,
    ACTIONS(213), 1,
      sym_ident,
    STATE(91), 1,
      aux_sym_var_decllist_repeat1,
    STATE(134), 1,
      sym_var,
  [1925] = 3,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      aux_sym_var_list_repeat1,
  [1935] = 3,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      aux_sym_exp_list_repeat1,
  [1945] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      aux_sym_var_list_repeat1,
  [1955] = 3,
    ACTIONS(198), 1,
      sym_method,
    STATE(89), 1,
      aux_sym_class_decl_repeat1,
    STATE(103), 1,
      sym_method_decl,
  [1965] = 3,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_DASH_GT,
    ACTIONS(227), 1,
      anon_sym_COLON_EQ,
  [1975] = 3,
    ACTIONS(141), 1,
      sym_ident,
    STATE(91), 1,
      aux_sym_var_decllist_repeat1,
    STATE(111), 1,
      sym_var,
  [1985] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_var_list_repeat1,
  [1995] = 3,
    ACTIONS(198), 1,
      sym_method,
    STATE(89), 1,
      aux_sym_class_decl_repeat1,
    STATE(124), 1,
      sym_method_decl,
  [2005] = 3,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    STATE(100), 1,
      aux_sym_exp_list_repeat1,
  [2015] = 3,
    ACTIONS(141), 1,
      sym_ident,
    STATE(98), 1,
      sym_var,
    STATE(151), 1,
      sym_var_list,
  [2025] = 2,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [2033] = 2,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(238), 1,
      sym_end,
  [2040] = 1,
    ACTIONS(240), 2,
      anon_sym_SEMI,
      sym_end,
  [2045] = 1,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2050] = 2,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(244), 1,
      sym_begin,
  [2057] = 2,
    ACTIONS(9), 1,
      sym_begin,
    STATE(77), 1,
      sym_block,
  [2064] = 2,
    ACTIONS(246), 1,
      sym_ident,
    STATE(152), 1,
      sym_fun,
  [2071] = 2,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(248), 1,
      sym_end,
  [2078] = 2,
    ACTIONS(250), 1,
      sym_ident,
    ACTIONS(252), 1,
      sym_begin,
  [2085] = 2,
    ACTIONS(252), 1,
      sym_begin,
    ACTIONS(254), 1,
      anon_sym_SEMI,
  [2092] = 2,
    ACTIONS(256), 1,
      sym_ident,
    STATE(125), 1,
      sym_classname,
  [2099] = 2,
    ACTIONS(256), 1,
      sym_ident,
    STATE(66), 1,
      sym_classname,
  [2106] = 2,
    ACTIONS(246), 1,
      sym_ident,
    STATE(131), 1,
      sym_fun,
  [2113] = 2,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      sym_end,
  [2120] = 2,
    ACTIONS(141), 1,
      sym_ident,
    STATE(105), 1,
      sym_var,
  [2127] = 2,
    ACTIONS(250), 1,
      sym_ident,
    ACTIONS(260), 1,
      sym_begin,
  [2134] = 2,
    ACTIONS(246), 1,
      sym_ident,
    STATE(135), 1,
      sym_fun,
  [2141] = 1,
    ACTIONS(262), 2,
      anon_sym_SEMI,
      sym_end,
  [2146] = 2,
    ACTIONS(9), 1,
      sym_begin,
    STATE(121), 1,
      sym_block,
  [2153] = 1,
    ACTIONS(264), 2,
      anon_sym_SEMI,
      sym_end,
  [2158] = 1,
    ACTIONS(266), 2,
      anon_sym_SEMI,
      sym_end,
  [2163] = 2,
    ACTIONS(9), 1,
      sym_begin,
    STATE(104), 1,
      sym_block,
  [2170] = 2,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    ACTIONS(268), 1,
      sym_end,
  [2177] = 1,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
  [2181] = 1,
    ACTIONS(272), 1,
      sym_method,
  [2185] = 1,
    ACTIONS(274), 1,
      anon_sym_SEMI,
  [2189] = 1,
    ACTIONS(276), 1,
      sym_else,
  [2193] = 1,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
  [2197] = 1,
    ACTIONS(278), 1,
      sym_end,
  [2201] = 1,
    ACTIONS(280), 1,
      anon_sym_LPAREN,
  [2205] = 1,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
  [2209] = 1,
    ACTIONS(284), 1,
      sym_begin,
  [2213] = 1,
    ACTIONS(286), 1,
      anon_sym_SEMI,
  [2217] = 1,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
  [2221] = 1,
    ACTIONS(290), 1,
      anon_sym_SEMI,
  [2225] = 1,
    ACTIONS(236), 1,
      anon_sym_SEMI,
  [2229] = 1,
    ACTIONS(292), 1,
      sym_begin,
  [2233] = 1,
    ACTIONS(294), 1,
      anon_sym_SEMI,
  [2237] = 1,
    ACTIONS(296), 1,
      sym_ident,
  [2241] = 1,
    ACTIONS(298), 1,
      anon_sym_SEMI,
  [2245] = 1,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
  [2249] = 1,
    ACTIONS(302), 1,
      anon_sym_LBRACK,
  [2253] = 1,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [2257] = 1,
    ACTIONS(306), 1,
      anon_sym_SEMI,
  [2261] = 1,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
  [2265] = 1,
    ACTIONS(310), 1,
      anon_sym_SEMI,
  [2269] = 1,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
  [2273] = 1,
    ACTIONS(314), 1,
      ts_builtin_sym_end,
  [2277] = 1,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
  [2281] = 1,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
  [2285] = 1,
    ACTIONS(320), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 71,
  [SMALL_STATE(4)] = 139,
  [SMALL_STATE(5)] = 207,
  [SMALL_STATE(6)] = 270,
  [SMALL_STATE(7)] = 333,
  [SMALL_STATE(8)] = 396,
  [SMALL_STATE(9)] = 423,
  [SMALL_STATE(10)] = 449,
  [SMALL_STATE(11)] = 473,
  [SMALL_STATE(12)] = 496,
  [SMALL_STATE(13)] = 519,
  [SMALL_STATE(14)] = 542,
  [SMALL_STATE(15)] = 565,
  [SMALL_STATE(16)] = 589,
  [SMALL_STATE(17)] = 615,
  [SMALL_STATE(18)] = 635,
  [SMALL_STATE(19)] = 655,
  [SMALL_STATE(20)] = 675,
  [SMALL_STATE(21)] = 695,
  [SMALL_STATE(22)] = 715,
  [SMALL_STATE(23)] = 735,
  [SMALL_STATE(24)] = 755,
  [SMALL_STATE(25)] = 797,
  [SMALL_STATE(26)] = 839,
  [SMALL_STATE(27)] = 881,
  [SMALL_STATE(28)] = 925,
  [SMALL_STATE(29)] = 967,
  [SMALL_STATE(30)] = 986,
  [SMALL_STATE(31)] = 1011,
  [SMALL_STATE(32)] = 1036,
  [SMALL_STATE(33)] = 1058,
  [SMALL_STATE(34)] = 1096,
  [SMALL_STATE(35)] = 1134,
  [SMALL_STATE(36)] = 1156,
  [SMALL_STATE(37)] = 1188,
  [SMALL_STATE(38)] = 1220,
  [SMALL_STATE(39)] = 1252,
  [SMALL_STATE(40)] = 1270,
  [SMALL_STATE(41)] = 1302,
  [SMALL_STATE(42)] = 1334,
  [SMALL_STATE(43)] = 1366,
  [SMALL_STATE(44)] = 1398,
  [SMALL_STATE(45)] = 1413,
  [SMALL_STATE(46)] = 1426,
  [SMALL_STATE(47)] = 1438,
  [SMALL_STATE(48)] = 1450,
  [SMALL_STATE(49)] = 1465,
  [SMALL_STATE(50)] = 1484,
  [SMALL_STATE(51)] = 1495,
  [SMALL_STATE(52)] = 1504,
  [SMALL_STATE(53)] = 1515,
  [SMALL_STATE(54)] = 1530,
  [SMALL_STATE(55)] = 1545,
  [SMALL_STATE(56)] = 1564,
  [SMALL_STATE(57)] = 1583,
  [SMALL_STATE(58)] = 1593,
  [SMALL_STATE(59)] = 1605,
  [SMALL_STATE(60)] = 1617,
  [SMALL_STATE(61)] = 1625,
  [SMALL_STATE(62)] = 1633,
  [SMALL_STATE(63)] = 1647,
  [SMALL_STATE(64)] = 1659,
  [SMALL_STATE(65)] = 1671,
  [SMALL_STATE(66)] = 1679,
  [SMALL_STATE(67)] = 1687,
  [SMALL_STATE(68)] = 1695,
  [SMALL_STATE(69)] = 1707,
  [SMALL_STATE(70)] = 1715,
  [SMALL_STATE(71)] = 1723,
  [SMALL_STATE(72)] = 1731,
  [SMALL_STATE(73)] = 1739,
  [SMALL_STATE(74)] = 1747,
  [SMALL_STATE(75)] = 1755,
  [SMALL_STATE(76)] = 1763,
  [SMALL_STATE(77)] = 1771,
  [SMALL_STATE(78)] = 1779,
  [SMALL_STATE(79)] = 1787,
  [SMALL_STATE(80)] = 1799,
  [SMALL_STATE(81)] = 1807,
  [SMALL_STATE(82)] = 1818,
  [SMALL_STATE(83)] = 1829,
  [SMALL_STATE(84)] = 1836,
  [SMALL_STATE(85)] = 1849,
  [SMALL_STATE(86)] = 1862,
  [SMALL_STATE(87)] = 1875,
  [SMALL_STATE(88)] = 1888,
  [SMALL_STATE(89)] = 1897,
  [SMALL_STATE(90)] = 1907,
  [SMALL_STATE(91)] = 1915,
  [SMALL_STATE(92)] = 1925,
  [SMALL_STATE(93)] = 1935,
  [SMALL_STATE(94)] = 1945,
  [SMALL_STATE(95)] = 1955,
  [SMALL_STATE(96)] = 1965,
  [SMALL_STATE(97)] = 1975,
  [SMALL_STATE(98)] = 1985,
  [SMALL_STATE(99)] = 1995,
  [SMALL_STATE(100)] = 2005,
  [SMALL_STATE(101)] = 2015,
  [SMALL_STATE(102)] = 2025,
  [SMALL_STATE(103)] = 2033,
  [SMALL_STATE(104)] = 2040,
  [SMALL_STATE(105)] = 2045,
  [SMALL_STATE(106)] = 2050,
  [SMALL_STATE(107)] = 2057,
  [SMALL_STATE(108)] = 2064,
  [SMALL_STATE(109)] = 2071,
  [SMALL_STATE(110)] = 2078,
  [SMALL_STATE(111)] = 2085,
  [SMALL_STATE(112)] = 2092,
  [SMALL_STATE(113)] = 2099,
  [SMALL_STATE(114)] = 2106,
  [SMALL_STATE(115)] = 2113,
  [SMALL_STATE(116)] = 2120,
  [SMALL_STATE(117)] = 2127,
  [SMALL_STATE(118)] = 2134,
  [SMALL_STATE(119)] = 2141,
  [SMALL_STATE(120)] = 2146,
  [SMALL_STATE(121)] = 2153,
  [SMALL_STATE(122)] = 2158,
  [SMALL_STATE(123)] = 2163,
  [SMALL_STATE(124)] = 2170,
  [SMALL_STATE(125)] = 2177,
  [SMALL_STATE(126)] = 2181,
  [SMALL_STATE(127)] = 2185,
  [SMALL_STATE(128)] = 2189,
  [SMALL_STATE(129)] = 2193,
  [SMALL_STATE(130)] = 2197,
  [SMALL_STATE(131)] = 2201,
  [SMALL_STATE(132)] = 2205,
  [SMALL_STATE(133)] = 2209,
  [SMALL_STATE(134)] = 2213,
  [SMALL_STATE(135)] = 2217,
  [SMALL_STATE(136)] = 2221,
  [SMALL_STATE(137)] = 2225,
  [SMALL_STATE(138)] = 2229,
  [SMALL_STATE(139)] = 2233,
  [SMALL_STATE(140)] = 2237,
  [SMALL_STATE(141)] = 2241,
  [SMALL_STATE(142)] = 2245,
  [SMALL_STATE(143)] = 2249,
  [SMALL_STATE(144)] = 2253,
  [SMALL_STATE(145)] = 2257,
  [SMALL_STATE(146)] = 2261,
  [SMALL_STATE(147)] = 2265,
  [SMALL_STATE(148)] = 2269,
  [SMALL_STATE(149)] = 2273,
  [SMALL_STATE(150)] = 2277,
  [SMALL_STATE(151)] = 2281,
  [SMALL_STATE(152)] = 2285,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(143),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fun, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lval, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fieldlab, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arr_idx, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_call, 3, 0, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_call, 4, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 5, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 6, 0, 7),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_stmt, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rval, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logic_bin, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_bin, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classname, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat2, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat2, 2, 0, 0), SHIFT_REPEAT(29),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_assgt, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp_list, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_loop, 4, 0, 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_new_obj, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_new_arr, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 9, 0, 9),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 6, 0, 6),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 8, 0, 9),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_decl, 7, 0, 8),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 7, 0, 9),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 8, 0, 11),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_decl, 8, 0, 10),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 9, 0, 11),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 10, 0, 11),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exp_list_repeat1, 2, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_var_list_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_var_list_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp_list, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_list, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_list, 1, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exp_list_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 8, 0, 10),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 3, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 6, 0, 12),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 7, 0, 13),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 7, 0, 8),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_decl_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [282] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sil(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
