#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 145
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_SEMI = 2,
  aux_sym_exp_token1 = 3,
  anon_sym_PLUS = 4,
  anon_sym_STAR = 5,
  anon_sym_DASH = 6,
  anon_sym_COMMA = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_not = 10,
  anon_sym_and = 11,
  anon_sym_or = 12,
  anon_sym_GT = 13,
  anon_sym_LT = 14,
  anon_sym_EQ = 15,
  sym_skip = 16,
  anon_sym_begin = 17,
  anon_sym_end = 18,
  anon_sym_while = 19,
  anon_sym_do = 20,
  anon_sym_if = 21,
  anon_sym_then = 22,
  anon_sym_else = 23,
  anon_sym_COLON_EQ = 24,
  anon_sym_procedure = 25,
  anon_sym_LPAREN = 26,
  anon_sym_RPAREN = 27,
  anon_sym_array = 28,
  anon_sym_LBRACK = 29,
  anon_sym_RBRACK = 30,
  anon_sym_class = 31,
  anon_sym_method = 32,
  anon_sym_new = 33,
  anon_sym_DASH_GT = 34,
  anon_sym_DOT = 35,
  anon_sym_print = 36,
  aux_sym_comment_token1 = 37,
  sym_prog = 38,
  sym_statement_list = 39,
  sym_statement = 40,
  sym_exp = 41,
  sym_exp_list = 42,
  sym_boolexp = 43,
  sym_block = 44,
  sym_while = 45,
  sym_if = 46,
  sym_var = 47,
  sym_var_assgt = 48,
  sym_rval = 49,
  sym_var_list = 50,
  sym_var_decllist = 51,
  sym_proc_decl = 52,
  sym_proc_call = 53,
  sym_new_arr = 54,
  sym_arr_idx = 55,
  sym_class_decl = 56,
  sym_method_decl = 57,
  sym_new_obj = 58,
  sym_field = 59,
  sym_method_call = 60,
  sym_print = 61,
  sym_comment = 62,
  aux_sym_statement_list_repeat1 = 63,
  aux_sym_statement_list_repeat2 = 64,
  aux_sym_exp_list_repeat1 = 65,
  aux_sym_var_list_repeat1 = 66,
  aux_sym_var_decllist_repeat1 = 67,
  aux_sym_class_decl_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_SEMI] = ";",
  [aux_sym_exp_token1] = "exp_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [sym_skip] = "skip",
  [anon_sym_begin] = "begin",
  [anon_sym_end] = "end",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_procedure] = "procedure",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_array] = "array",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_class] = "class",
  [anon_sym_method] = "method",
  [anon_sym_new] = "new",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DOT] = ".",
  [anon_sym_print] = "print",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_prog] = "prog",
  [sym_statement_list] = "statement_list",
  [sym_statement] = "statement",
  [sym_exp] = "exp",
  [sym_exp_list] = "exp_list",
  [sym_boolexp] = "boolexp",
  [sym_block] = "block",
  [sym_while] = "while",
  [sym_if] = "if",
  [sym_var] = "var",
  [sym_var_assgt] = "var_assgt",
  [sym_rval] = "rval",
  [sym_var_list] = "var_list",
  [sym_var_decllist] = "var_decllist",
  [sym_proc_decl] = "proc_decl",
  [sym_proc_call] = "proc_call",
  [sym_new_arr] = "new_arr",
  [sym_arr_idx] = "arr_idx",
  [sym_class_decl] = "class_decl",
  [sym_method_decl] = "method_decl",
  [sym_new_obj] = "new_obj",
  [sym_field] = "field",
  [sym_method_call] = "method_call",
  [sym_print] = "print",
  [sym_comment] = "comment",
  [aux_sym_statement_list_repeat1] = "statement_list_repeat1",
  [aux_sym_statement_list_repeat2] = "statement_list_repeat2",
  [aux_sym_exp_list_repeat1] = "exp_list_repeat1",
  [aux_sym_var_list_repeat1] = "var_list_repeat1",
  [aux_sym_var_decllist_repeat1] = "var_decllist_repeat1",
  [aux_sym_class_decl_repeat1] = "class_decl_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_exp_token1] = aux_sym_exp_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_skip] = sym_skip,
  [anon_sym_begin] = anon_sym_begin,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_procedure] = anon_sym_procedure,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_method] = anon_sym_method,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_print] = anon_sym_print,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_prog] = sym_prog,
  [sym_statement_list] = sym_statement_list,
  [sym_statement] = sym_statement,
  [sym_exp] = sym_exp,
  [sym_exp_list] = sym_exp_list,
  [sym_boolexp] = sym_boolexp,
  [sym_block] = sym_block,
  [sym_while] = sym_while,
  [sym_if] = sym_if,
  [sym_var] = sym_var,
  [sym_var_assgt] = sym_var_assgt,
  [sym_rval] = sym_rval,
  [sym_var_list] = sym_var_list,
  [sym_var_decllist] = sym_var_decllist,
  [sym_proc_decl] = sym_proc_decl,
  [sym_proc_call] = sym_proc_call,
  [sym_new_arr] = sym_new_arr,
  [sym_arr_idx] = sym_arr_idx,
  [sym_class_decl] = sym_class_decl,
  [sym_method_decl] = sym_method_decl,
  [sym_new_obj] = sym_new_obj,
  [sym_field] = sym_field,
  [sym_method_call] = sym_method_call,
  [sym_print] = sym_print,
  [sym_comment] = sym_comment,
  [aux_sym_statement_list_repeat1] = aux_sym_statement_list_repeat1,
  [aux_sym_statement_list_repeat2] = aux_sym_statement_list_repeat2,
  [aux_sym_exp_list_repeat1] = aux_sym_exp_list_repeat1,
  [aux_sym_var_list_repeat1] = aux_sym_var_list_repeat1,
  [aux_sym_var_decllist_repeat1] = aux_sym_var_decllist_repeat1,
  [aux_sym_class_decl_repeat1] = aux_sym_class_decl_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_exp_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_skip] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_begin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_procedure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_method] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_prog] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_list] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym_exp_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolexp] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_var_assgt] = {
    .visible = true,
    .named = true,
  },
  [sym_rval] = {
    .visible = true,
    .named = true,
  },
  [sym_var_list] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decllist] = {
    .visible = true,
    .named = true,
  },
  [sym_proc_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_proc_call] = {
    .visible = true,
    .named = true,
  },
  [sym_new_arr] = {
    .visible = true,
    .named = true,
  },
  [sym_arr_idx] = {
    .visible = true,
    .named = true,
  },
  [sym_class_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_method_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_new_obj] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_print] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_list_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exp_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_decllist_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_branchOn = 3,
  field_declarations = 4,
  field_doBlock = 5,
  field_elseBlock = 6,
  field_methodName = 7,
  field_name = 8,
  field_object = 9,
  field_params = 10,
  field_thenBlock = 11,
  field_whileCond = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_branchOn] = "branchOn",
  [field_declarations] = "declarations",
  [field_doBlock] = "doBlock",
  [field_elseBlock] = "elseBlock",
  [field_methodName] = "methodName",
  [field_name] = "name",
  [field_object] = "object",
  [field_params] = "params",
  [field_thenBlock] = "thenBlock",
  [field_whileCond] = "whileCond",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 1},
  [10] = {.index = 18, .length = 4},
  [11] = {.index = 22, .length = 2},
  [12] = {.index = 24, .length = 2},
  [13] = {.index = 26, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_doBlock, 3},
    {field_whileCond, 1},
  [4] =
    {field_args, 2},
    {field_name, 0},
  [6] =
    {field_methodName, 2},
    {field_object, 0},
  [8] =
    {field_branchOn, 1},
    {field_elseBlock, 5},
    {field_thenBlock, 3},
  [11] =
    {field_args, 4},
    {field_methodName, 2},
    {field_object, 0},
  [14] =
    {field_body, 6},
    {field_name, 1},
    {field_params, 3},
  [17] =
    {field_name, 1},
  [18] =
    {field_body, 7},
    {field_declarations, 6},
    {field_name, 1},
    {field_params, 3},
  [22] =
    {field_name, 1},
    {field_params, 3},
  [24] =
    {field_body, 5},
    {field_name, 1},
  [26] =
    {field_body, 6},
    {field_declarations, 5},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '%', 24,
        '(', 18,
        ')', 19,
        '*', 9,
        '+', 8,
        ',', 12,
        '-', 11,
        '.', 23,
        ':', 2,
        ';', 6,
        '<', 14,
        '=', 15,
        '>', 13,
        '[', 20,
        ']', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '-') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '%', 24,
        '(', 18,
        ')', 19,
        '*', 9,
        '+', 8,
        ',', 12,
        '-', 3,
        '.', 23,
        ':', 2,
        ';', 6,
        '<', 14,
        '=', 15,
        '>', 13,
        '[', 20,
        ']', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'm', 8,
        'n', 9,
        'o', 10,
        'p', 11,
        's', 12,
        't', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'k') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(30);
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'w') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'h') ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'y') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_skip);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_begin);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 67:
      if (lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_method);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_procedure);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 4},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym_exp_token1] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_skip] = ACTIONS(1),
    [anon_sym_begin] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_procedure] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_method] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_prog] = STATE(144),
    [sym_statement_list] = STATE(138),
    [sym_statement] = STATE(48),
    [sym_block] = STATE(53),
    [sym_while] = STATE(53),
    [sym_if] = STATE(53),
    [sym_var] = STATE(67),
    [sym_var_assgt] = STATE(53),
    [sym_proc_decl] = STATE(53),
    [sym_proc_call] = STATE(53),
    [sym_new_arr] = STATE(53),
    [sym_arr_idx] = STATE(8),
    [sym_class_decl] = STATE(53),
    [sym_new_obj] = STATE(53),
    [sym_field] = STATE(34),
    [sym_method_call] = STATE(53),
    [sym_print] = STATE(53),
    [sym_comment] = STATE(24),
    [aux_sym_statement_list_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ident] = ACTIONS(5),
    [sym_skip] = ACTIONS(7),
    [anon_sym_begin] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_procedure] = ACTIONS(15),
    [anon_sym_array] = ACTIONS(17),
    [anon_sym_class] = ACTIONS(19),
    [anon_sym_print] = ACTIONS(21),
    [aux_sym_comment_token1] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      anon_sym_begin,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_procedure,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(19), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(3), 1,
      aux_sym_statement_list_repeat1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(24), 1,
      sym_comment,
    STATE(34), 1,
      sym_field,
    STATE(48), 1,
      sym_statement,
    STATE(67), 1,
      sym_var,
    STATE(125), 1,
      sym_statement_list,
    STATE(53), 11,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
  [65] = 17,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      anon_sym_begin,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_procedure,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(19), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(4), 1,
      aux_sym_statement_list_repeat1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(26), 1,
      sym_comment,
    STATE(34), 1,
      sym_field,
    STATE(51), 1,
      sym_statement,
    STATE(67), 1,
      sym_var,
    STATE(53), 11,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
  [127] = 17,
    ACTIONS(25), 1,
      sym_ident,
    ACTIONS(28), 1,
      sym_skip,
    ACTIONS(31), 1,
      anon_sym_begin,
    ACTIONS(34), 1,
      anon_sym_while,
    ACTIONS(37), 1,
      anon_sym_if,
    ACTIONS(40), 1,
      anon_sym_procedure,
    ACTIONS(43), 1,
      anon_sym_array,
    ACTIONS(46), 1,
      anon_sym_class,
    ACTIONS(49), 1,
      anon_sym_print,
    ACTIONS(52), 1,
      aux_sym_comment_token1,
    STATE(4), 1,
      aux_sym_statement_list_repeat1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(31), 1,
      sym_comment,
    STATE(34), 1,
      sym_field,
    STATE(67), 1,
      sym_var,
    STATE(128), 1,
      sym_statement,
    STATE(53), 11,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
  [189] = 15,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      anon_sym_begin,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_procedure,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(19), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(34), 1,
      sym_field,
    STATE(66), 1,
      sym_statement,
    STATE(67), 1,
      sym_var,
    STATE(53), 12,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
      sym_comment,
  [246] = 15,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      anon_sym_begin,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_procedure,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(19), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(34), 1,
      sym_field,
    STATE(61), 1,
      sym_statement,
    STATE(67), 1,
      sym_var,
    STATE(53), 12,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
      sym_comment,
  [303] = 15,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      sym_skip,
    ACTIONS(9), 1,
      anon_sym_begin,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_procedure,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(19), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_print,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    STATE(8), 1,
      sym_arr_idx,
    STATE(34), 1,
      sym_field,
    STATE(67), 1,
      sym_var,
    STATE(143), 1,
      sym_statement,
    STATE(53), 12,
      sym_block,
      sym_while,
      sym_if,
      sym_var_assgt,
      sym_proc_decl,
      sym_proc_call,
      sym_new_arr,
      sym_class_decl,
      sym_new_obj,
      sym_method_call,
      sym_print,
      sym_comment,
  [360] = 1,
    ACTIONS(55), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_begin,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      aux_sym_comment_token1,
  [386] = 1,
    ACTIONS(57), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_begin,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      aux_sym_comment_token1,
  [412] = 1,
    ACTIONS(59), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_begin,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      aux_sym_comment_token1,
  [438] = 2,
    ACTIONS(55), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
    ACTIONS(61), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [464] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(61), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [496] = 1,
    ACTIONS(71), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [516] = 1,
    ACTIONS(61), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [536] = 1,
    ACTIONS(73), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [556] = 1,
    ACTIONS(75), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [576] = 1,
    ACTIONS(77), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [596] = 1,
    ACTIONS(79), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [616] = 1,
    ACTIONS(81), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
      anon_sym_end,
      anon_sym_do,
      anon_sym_then,
      anon_sym_else,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [636] = 5,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      sym_ident,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(54), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
    ACTIONS(87), 8,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
  [661] = 2,
    ACTIONS(91), 1,
      sym_ident,
    ACTIONS(89), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_skip,
      anon_sym_begin,
      anon_sym_end,
      anon_sym_while,
      anon_sym_if,
      anon_sym_else,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
      aux_sym_comment_token1,
  [680] = 5,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      sym_ident,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(64), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
    ACTIONS(87), 8,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
  [705] = 11,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_not,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(69), 1,
      sym_exp,
    STATE(96), 1,
      sym_boolexp,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [741] = 4,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    ACTIONS(107), 2,
      anon_sym_SEMI,
      aux_sym_comment_token1,
    ACTIONS(109), 8,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
  [763] = 12,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(17), 1,
      anon_sym_array,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_new,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(46), 1,
      sym_exp,
    STATE(56), 1,
      sym_rval,
    STATE(57), 1,
      sym_new_arr,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [801] = 4,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    ACTIONS(107), 2,
      anon_sym_SEMI,
      aux_sym_comment_token1,
    ACTIONS(109), 8,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
  [823] = 11,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_not,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(69), 1,
      sym_exp,
    STATE(109), 1,
      sym_boolexp,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [859] = 11,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_not,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(69), 1,
      sym_exp,
    STATE(85), 1,
      sym_boolexp,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [895] = 11,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_not,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(69), 1,
      sym_exp,
    STATE(88), 1,
      sym_boolexp,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [931] = 10,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(60), 1,
      sym_exp,
    STATE(127), 1,
      sym_exp_list,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [963] = 3,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(107), 1,
      anon_sym_SEMI,
    ACTIONS(109), 9,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
      aux_sym_comment_token1,
  [981] = 10,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(60), 1,
      sym_exp,
    STATE(136), 1,
      sym_exp_list,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1013] = 2,
    ACTIONS(85), 1,
      sym_ident,
    ACTIONS(87), 9,
      sym_skip,
      anon_sym_begin,
      anon_sym_while,
      anon_sym_if,
      anon_sym_procedure,
      anon_sym_array,
      anon_sym_class,
      anon_sym_print,
      aux_sym_comment_token1,
  [1028] = 2,
    ACTIONS(55), 5,
      anon_sym_COLON_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
      anon_sym_DOT,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1043] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(50), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1069] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(99), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1095] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(83), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1121] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(100), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1147] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(16), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1173] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(47), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1199] = 8,
    ACTIONS(95), 1,
      aux_sym_exp_token1,
    ACTIONS(97), 1,
      anon_sym_DASH,
    ACTIONS(113), 1,
      sym_ident,
    STATE(8), 1,
      sym_field,
    STATE(11), 1,
      sym_arr_idx,
    STATE(12), 1,
      sym_var,
    STATE(13), 1,
      sym_exp,
    STATE(14), 2,
      sym_proc_call,
      sym_method_call,
  [1225] = 7,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(68), 1,
      sym_block,
    STATE(75), 1,
      aux_sym_var_decllist_repeat1,
    STATE(87), 1,
      sym_var,
    STATE(113), 1,
      sym_var_decllist,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1248] = 7,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(75), 1,
      aux_sym_var_decllist_repeat1,
    STATE(87), 1,
      sym_var,
    STATE(111), 1,
      sym_block,
    STATE(119), 1,
      sym_var_decllist,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1271] = 7,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(75), 1,
      aux_sym_var_decllist_repeat1,
    STATE(87), 1,
      sym_var,
    STATE(121), 1,
      sym_block,
    STATE(122), 1,
      sym_var_decllist,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1294] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1308] = 2,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1320] = 2,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1332] = 4,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(127), 1,
      anon_sym_SEMI,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(59), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1347] = 5,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_var,
    STATE(130), 1,
      sym_var_list,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1364] = 2,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(131), 4,
      anon_sym_and,
      anon_sym_or,
      anon_sym_do,
      anon_sym_then,
  [1375] = 4,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(54), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1390] = 5,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_var,
    STATE(134), 1,
      sym_var_list,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1407] = 1,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1415] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1427] = 4,
    ACTIONS(113), 1,
      sym_ident,
    STATE(62), 1,
      sym_var,
    STATE(142), 1,
      sym_var_list,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1441] = 1,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1449] = 1,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1457] = 3,
    ACTIONS(141), 1,
      aux_sym_comment_token1,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1469] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1481] = 4,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      aux_sym_exp_list_repeat1,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1495] = 1,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1503] = 5,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      aux_sym_var_list_repeat1,
  [1519] = 1,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1527] = 3,
    ACTIONS(23), 1,
      aux_sym_comment_token1,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_end,
    STATE(58), 2,
      sym_comment,
      aux_sym_statement_list_repeat2,
  [1539] = 1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1547] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1555] = 5,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(162), 1,
      anon_sym_COLON_EQ,
  [1571] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1579] = 2,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(166), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ,
  [1589] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1597] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1605] = 4,
    ACTIONS(172), 1,
      sym_ident,
    STATE(72), 1,
      aux_sym_var_decllist_repeat1,
    STATE(108), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1619] = 1,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1627] = 1,
    ACTIONS(177), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1635] = 4,
    ACTIONS(113), 1,
      sym_ident,
    STATE(72), 1,
      aux_sym_var_decllist_repeat1,
    STATE(92), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1649] = 1,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1657] = 1,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1665] = 1,
    ACTIONS(183), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_end,
      anon_sym_else,
      aux_sym_comment_token1,
  [1673] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(45), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1684] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(95), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1695] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(98), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1706] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(84), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1717] = 2,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1726] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1737] = 2,
    ACTIONS(189), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(191), 2,
      anon_sym_do,
      anon_sym_then,
  [1746] = 4,
    ACTIONS(193), 1,
      anon_sym_end,
    ACTIONS(195), 1,
      anon_sym_method,
    STATE(103), 1,
      aux_sym_class_decl_repeat1,
    STATE(118), 1,
      sym_method_decl,
  [1759] = 4,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(197), 1,
      anon_sym_SEMI,
    ACTIONS(199), 1,
      anon_sym_begin,
  [1772] = 2,
    ACTIONS(131), 2,
      anon_sym_do,
      anon_sym_then,
    ACTIONS(189), 2,
      anon_sym_and,
      anon_sym_or,
  [1781] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(104), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1792] = 4,
    ACTIONS(195), 1,
      anon_sym_method,
    ACTIONS(201), 1,
      anon_sym_end,
    STATE(107), 1,
      aux_sym_class_decl_repeat1,
    STATE(115), 1,
      sym_method_decl,
  [1805] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(101), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1816] = 4,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(203), 1,
      anon_sym_SEMI,
    ACTIONS(205), 1,
      anon_sym_begin,
  [1829] = 3,
    ACTIONS(113), 1,
      sym_ident,
    STATE(9), 1,
      sym_var,
    STATE(8), 2,
      sym_arr_idx,
      sym_field,
  [1840] = 1,
    ACTIONS(207), 4,
      anon_sym_and,
      anon_sym_or,
      anon_sym_do,
      anon_sym_then,
  [1847] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
  [1857] = 2,
    ACTIONS(211), 1,
      anon_sym_then,
    ACTIONS(189), 2,
      anon_sym_and,
      anon_sym_or,
  [1865] = 3,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_var_list_repeat1,
  [1875] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(216), 1,
      anon_sym_LPAREN,
  [1885] = 2,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1893] = 2,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    ACTIONS(123), 2,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1901] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
  [1911] = 3,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_var_list_repeat1,
  [1921] = 3,
    ACTIONS(195), 1,
      anon_sym_method,
    STATE(106), 1,
      aux_sym_class_decl_repeat1,
    STATE(114), 1,
      sym_method_decl,
  [1931] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
  [1941] = 3,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(105), 1,
      aux_sym_exp_list_repeat1,
  [1951] = 3,
    ACTIONS(231), 1,
      anon_sym_method,
    STATE(106), 1,
      aux_sym_class_decl_repeat1,
    STATE(129), 1,
      sym_method_decl,
  [1961] = 3,
    ACTIONS(195), 1,
      anon_sym_method,
    STATE(106), 1,
      aux_sym_class_decl_repeat1,
    STATE(117), 1,
      sym_method_decl,
  [1971] = 3,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(234), 1,
      anon_sym_SEMI,
  [1981] = 2,
    ACTIONS(236), 1,
      anon_sym_do,
    ACTIONS(189), 2,
      anon_sym_and,
      anon_sym_or,
  [1989] = 3,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      aux_sym_exp_list_repeat1,
  [1999] = 1,
    ACTIONS(240), 2,
      anon_sym_SEMI,
      anon_sym_end,
  [2004] = 2,
    ACTIONS(205), 1,
      anon_sym_begin,
    ACTIONS(242), 1,
      sym_ident,
  [2011] = 2,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(71), 1,
      sym_block,
  [2018] = 2,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(246), 1,
      anon_sym_end,
  [2025] = 2,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(248), 1,
      anon_sym_end,
  [2032] = 2,
    ACTIONS(242), 1,
      sym_ident,
    ACTIONS(250), 1,
      anon_sym_begin,
  [2039] = 2,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      anon_sym_end,
  [2046] = 2,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(254), 1,
      anon_sym_end,
  [2053] = 2,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(120), 1,
      sym_block,
  [2060] = 1,
    ACTIONS(256), 2,
      anon_sym_SEMI,
      anon_sym_end,
  [2065] = 1,
    ACTIONS(258), 2,
      anon_sym_SEMI,
      anon_sym_end,
  [2070] = 2,
    ACTIONS(9), 1,
      anon_sym_begin,
    STATE(123), 1,
      sym_block,
  [2077] = 1,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_end,
  [2082] = 1,
    ACTIONS(262), 1,
      anon_sym_SEMI,
  [2086] = 1,
    ACTIONS(264), 1,
      anon_sym_end,
  [2090] = 1,
    ACTIONS(266), 1,
      anon_sym_SEMI,
  [2094] = 1,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
  [2098] = 1,
    ACTIONS(270), 1,
      anon_sym_SEMI,
  [2102] = 1,
    ACTIONS(244), 1,
      anon_sym_SEMI,
  [2106] = 1,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [2110] = 1,
    ACTIONS(274), 1,
      anon_sym_method,
  [2114] = 1,
    ACTIONS(276), 1,
      sym_ident,
  [2118] = 1,
    ACTIONS(278), 1,
      anon_sym_SEMI,
  [2122] = 1,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
  [2126] = 1,
    ACTIONS(282), 1,
      anon_sym_SEMI,
  [2130] = 1,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [2134] = 1,
    ACTIONS(286), 1,
      anon_sym_SEMI,
  [2138] = 1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
  [2142] = 1,
    ACTIONS(290), 1,
      anon_sym_LBRACK,
  [2146] = 1,
    ACTIONS(292), 1,
      anon_sym_begin,
  [2150] = 1,
    ACTIONS(294), 1,
      anon_sym_begin,
  [2154] = 1,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
  [2158] = 1,
    ACTIONS(298), 1,
      anon_sym_else,
  [2162] = 1,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 65,
  [SMALL_STATE(4)] = 127,
  [SMALL_STATE(5)] = 189,
  [SMALL_STATE(6)] = 246,
  [SMALL_STATE(7)] = 303,
  [SMALL_STATE(8)] = 360,
  [SMALL_STATE(9)] = 386,
  [SMALL_STATE(10)] = 412,
  [SMALL_STATE(11)] = 438,
  [SMALL_STATE(12)] = 464,
  [SMALL_STATE(13)] = 496,
  [SMALL_STATE(14)] = 516,
  [SMALL_STATE(15)] = 536,
  [SMALL_STATE(16)] = 556,
  [SMALL_STATE(17)] = 576,
  [SMALL_STATE(18)] = 596,
  [SMALL_STATE(19)] = 616,
  [SMALL_STATE(20)] = 636,
  [SMALL_STATE(21)] = 661,
  [SMALL_STATE(22)] = 680,
  [SMALL_STATE(23)] = 705,
  [SMALL_STATE(24)] = 741,
  [SMALL_STATE(25)] = 763,
  [SMALL_STATE(26)] = 801,
  [SMALL_STATE(27)] = 823,
  [SMALL_STATE(28)] = 859,
  [SMALL_STATE(29)] = 895,
  [SMALL_STATE(30)] = 931,
  [SMALL_STATE(31)] = 963,
  [SMALL_STATE(32)] = 981,
  [SMALL_STATE(33)] = 1013,
  [SMALL_STATE(34)] = 1028,
  [SMALL_STATE(35)] = 1043,
  [SMALL_STATE(36)] = 1069,
  [SMALL_STATE(37)] = 1095,
  [SMALL_STATE(38)] = 1121,
  [SMALL_STATE(39)] = 1147,
  [SMALL_STATE(40)] = 1173,
  [SMALL_STATE(41)] = 1199,
  [SMALL_STATE(42)] = 1225,
  [SMALL_STATE(43)] = 1248,
  [SMALL_STATE(44)] = 1271,
  [SMALL_STATE(45)] = 1294,
  [SMALL_STATE(46)] = 1308,
  [SMALL_STATE(47)] = 1320,
  [SMALL_STATE(48)] = 1332,
  [SMALL_STATE(49)] = 1347,
  [SMALL_STATE(50)] = 1364,
  [SMALL_STATE(51)] = 1375,
  [SMALL_STATE(52)] = 1390,
  [SMALL_STATE(53)] = 1407,
  [SMALL_STATE(54)] = 1415,
  [SMALL_STATE(55)] = 1427,
  [SMALL_STATE(56)] = 1441,
  [SMALL_STATE(57)] = 1449,
  [SMALL_STATE(58)] = 1457,
  [SMALL_STATE(59)] = 1469,
  [SMALL_STATE(60)] = 1481,
  [SMALL_STATE(61)] = 1495,
  [SMALL_STATE(62)] = 1503,
  [SMALL_STATE(63)] = 1519,
  [SMALL_STATE(64)] = 1527,
  [SMALL_STATE(65)] = 1539,
  [SMALL_STATE(66)] = 1547,
  [SMALL_STATE(67)] = 1555,
  [SMALL_STATE(68)] = 1571,
  [SMALL_STATE(69)] = 1579,
  [SMALL_STATE(70)] = 1589,
  [SMALL_STATE(71)] = 1597,
  [SMALL_STATE(72)] = 1605,
  [SMALL_STATE(73)] = 1619,
  [SMALL_STATE(74)] = 1627,
  [SMALL_STATE(75)] = 1635,
  [SMALL_STATE(76)] = 1649,
  [SMALL_STATE(77)] = 1657,
  [SMALL_STATE(78)] = 1665,
  [SMALL_STATE(79)] = 1673,
  [SMALL_STATE(80)] = 1684,
  [SMALL_STATE(81)] = 1695,
  [SMALL_STATE(82)] = 1706,
  [SMALL_STATE(83)] = 1717,
  [SMALL_STATE(84)] = 1726,
  [SMALL_STATE(85)] = 1737,
  [SMALL_STATE(86)] = 1746,
  [SMALL_STATE(87)] = 1759,
  [SMALL_STATE(88)] = 1772,
  [SMALL_STATE(89)] = 1781,
  [SMALL_STATE(90)] = 1792,
  [SMALL_STATE(91)] = 1805,
  [SMALL_STATE(92)] = 1816,
  [SMALL_STATE(93)] = 1829,
  [SMALL_STATE(94)] = 1840,
  [SMALL_STATE(95)] = 1847,
  [SMALL_STATE(96)] = 1857,
  [SMALL_STATE(97)] = 1865,
  [SMALL_STATE(98)] = 1875,
  [SMALL_STATE(99)] = 1885,
  [SMALL_STATE(100)] = 1893,
  [SMALL_STATE(101)] = 1901,
  [SMALL_STATE(102)] = 1911,
  [SMALL_STATE(103)] = 1921,
  [SMALL_STATE(104)] = 1931,
  [SMALL_STATE(105)] = 1941,
  [SMALL_STATE(106)] = 1951,
  [SMALL_STATE(107)] = 1961,
  [SMALL_STATE(108)] = 1971,
  [SMALL_STATE(109)] = 1981,
  [SMALL_STATE(110)] = 1989,
  [SMALL_STATE(111)] = 1999,
  [SMALL_STATE(112)] = 2004,
  [SMALL_STATE(113)] = 2011,
  [SMALL_STATE(114)] = 2018,
  [SMALL_STATE(115)] = 2025,
  [SMALL_STATE(116)] = 2032,
  [SMALL_STATE(117)] = 2039,
  [SMALL_STATE(118)] = 2046,
  [SMALL_STATE(119)] = 2053,
  [SMALL_STATE(120)] = 2060,
  [SMALL_STATE(121)] = 2065,
  [SMALL_STATE(122)] = 2070,
  [SMALL_STATE(123)] = 2077,
  [SMALL_STATE(124)] = 2082,
  [SMALL_STATE(125)] = 2086,
  [SMALL_STATE(126)] = 2090,
  [SMALL_STATE(127)] = 2094,
  [SMALL_STATE(128)] = 2098,
  [SMALL_STATE(129)] = 2102,
  [SMALL_STATE(130)] = 2106,
  [SMALL_STATE(131)] = 2110,
  [SMALL_STATE(132)] = 2114,
  [SMALL_STATE(133)] = 2118,
  [SMALL_STATE(134)] = 2122,
  [SMALL_STATE(135)] = 2126,
  [SMALL_STATE(136)] = 2130,
  [SMALL_STATE(137)] = 2134,
  [SMALL_STATE(138)] = 2138,
  [SMALL_STATE(139)] = 2142,
  [SMALL_STATE(140)] = 2146,
  [SMALL_STATE(141)] = 2150,
  [SMALL_STATE(142)] = 2154,
  [SMALL_STATE(143)] = 2158,
  [SMALL_STATE(144)] = 2162,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arr_idx, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_call, 3, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_call, 4, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 5, 0, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 6, 0, 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_statement_list_repeat1, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat1, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_new_obj, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rval, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_assgt, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat2, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_list_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp_list, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 4, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_list, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_new_arr, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_list, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6, 0, 6),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_decl, 7, 0, 8),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 7, 0, 9),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proc_decl, 8, 0, 10),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 8, 0, 9),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 8, 0, 11),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 9, 0, 9),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 9, 0, 11),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_decl, 10, 0, 11),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exp_list_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_var_list_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolexp, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_var_list_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_list, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exp_list_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp_list, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 6, 0, 12),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decllist, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 7, 0, 13),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 7, 0, 8),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_decl, 8, 0, 10),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_decl_repeat1, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_var_decllist_repeat1, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 1, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sil(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
